export enum ElemMaitrisesMecanismEnum {
    ABNEGATION = "ABNEGATION",
    ALTERNANCE = "ALTERNANCE",
    ALTERNANCE_2 = "ALTERNANCE_2",
    ANATOMIE = "ANATOMIE",
    CONCENTRATION_ELEMENTAIRE = "CONCENTRATION_ELEMENTAIRE",
    INFLEXIBILITE_2 = "INFLEXIBILITE_2",
    COEUR_HUPPERMAGE = "COEUR_HUPPERMAGE"
}