export enum KeyEnum {
    KEY_BUILD = "KEY_BUILD",
    KEY_LANG = "KEY_LANG",
    KEY_CRAFTABLE_CHOICE = "KEY_CRAFTABLE_CHOICE",
    KEY_ITEM_LEVEL = "KEY_ITEM_LEVEL",
    KEY_ITEM_TYPE = "KEY_ITEM_TYPE",
    KEY_MAITRISES = "KEY_MAITRISES",
    KEY_MAJOR_PRESENT = "KEY_MAJOR_PRESENT",
    KEY_MODIFIER_ELEM_MAITRISE = "KEY_MODIFIER_ELEM_MAITRISE",
    KEY_ONLY_NO_SECONDARY = "KEY_ONLY_NO_SECONDARY",
    KEY_RARETE_ITEM = "KEY_RARETE_ITEM",
    KEY_RESISTANCES = "KEY_RESISTANCES",
    KEY_SEARCH_ITEM_NAME = "KEY_SEARCH_ITEM_NAME",
    KEY_SORT_CHOICE = "KEY_SORT_CHOICE",
    KEY_SAVE_BUILD = "KEY_SAVE_BUILD",
    KEY_NAME_BUILD = "KEY_NAME_BUILD",
    KEY_IMPORT_BUILD = "KEY_IMPORT_BUILD",
    KEY_ONLY_NO_ELEM = "KEY_ONLY_NO_ELEM"
}