export enum SortChoiceEnum {
    POIDS = "POIDS",
    MAITRISES = "MAITRISES",
    RESISTANCES = "RESISTANCES",
    EQUILIBRE = "EQUILIBRE",
    PARADE_ARMURE_DONNEE = "PARADE_ARMURE_DONNEE",
    POINT_DE_VIE = "POINT_DE_VIE"
}