import json

# Dictionnaire des descriptions en français extraites de la page
descriptions_fr = {
    "Détermination": "-15 % Dommages indirects reçus.",
    "Ténacité": "En fin de tour, si le porteur de l'état a 2 PA ou plus :\n25 Résistance Élémentaire (1 tour).",
    "Solidité": "Réduit les dommages directs reçus supérieurs à 20 % des PV max de 400 % du niveau (une fois par tour de table).",
    "Réprobation": "-20 Volonté.\nRéduit de 1 la prochaine perte (+ une perte tous les 2 niveaux) de PA subie.\nL'effet se réapplique à chaque tour.",
    "Frénésie": "-20% Dommages Infligés.\nEn début de tour :\n10% Dommages Infligés par ennemi touché dans le tour précédent.",
    "Dimensionnalité": "Au premier tour du porteur de l'état :\n1 PW (non-régénérable).",
    "Retour PA": "Regagne 1 PA en tuant un ennemi (2 activations par tour).",
    "Sauvegarde": "En fin de tour :\nLes PA non utilisés sont transmis au tour suivant (max 1 PA).",
    "Ruine cyclique": "20 % Dommages indirects dans les tours de table pairs.",
    "Ravage secondaire": "En début de combat :\n3 % Coup Critique, 3 % Parade, 3 Volonté.",
    "Dérobade lente": "3 % Parade par tour (max 40).",
    "Persistance": "En fin de tour, si le porteur de l'état a 6 PA ou plus :\n60 Résistance Élémentaire (2 tours).",
    "Fureur": "-15% Dommages Infligés.\nEn début de tour :\n5% Dommages Infligés par entité touchée dans le tour précédent.",
    "Retour PM": "Regagne 1 PM en tuant un ennemi (2 activations par tour).",
    "Clameur": "-20 Volonté.\nRéduit de 1 la prochaine perte (+ une perte tous les 2 niveaux) de PM subie.\nL'effet se réapplique à chaque tour.",
    "Focalisation": "-15% Dommages Infligés.\nEn début de tour :\n25% Dommages Infligés si un seul ennemi a été touché au tour précédent.",
    "Expert des Parades": "-50 Résistance Élémentaire.\n-15 % Dommages reçus lors d'une Parade.",
    "Secret de la vie": "En début de combat :\nRéduit la Maîtrise Soin à 0.\n10 % Soins réalisés.",
    "Ruine": "5 % Dommages indirects.",
    "Dévastation": "1 PW.\n-30 Volonté (+10 Volonté par niveau).",
    "Ravage": "En début de combat :\nToutes les Maîtrises : 5 % du niveau.\nToutes les Résistances : +3.",
    "Carnage": "Lorsque les PV sont supérieurs à 90% :\n15 % du niveau en Maîtrise élémentaire.",
    "Cicatrisation": "5 % point de vie (bonus sur le modificateur de PV).",
    "Embuscade": "2 % aux Dommages Infligés aux cibles au contact.",
    "Dérobade": "En début de combat :\n5 % Parade (1 tour).",
    "Fermeté": "Après avoir subi une perte de 3 PA : 10 Volonté (3 tours).",
    "Légèreté": "Après avoir subi une perte de 3 PM :\n10 Volonté (3 tours).",
    "Topologie": "Au début du combat :\nToute l'Esquive du porteur de l'état est convertie en Armure avec un ratio de 1 pour 1.\nL'Esquive convertie est perdue.",
    "Théorie de la matière": "50 % Coup Critique.\n-50 % Dommages et Soins.",
    "Endurance": "-5 % aux malus de caractéristiques reçus.\nConcerne tous les malus de caractéristiques (Maîtrises, Résistances, Armure, Coup Critique...) reçus en combat, lancés par une entité autre que le porteur de l'état.\nLa valeur est toujours arrondie à l'inférieur.",
    "Ecailles de lune": "3 % Armure reçue.",
    "Vélocité": "1 PM.\n-20% Dommages Infligés.",
    "Vivacité": "1 PA.\n-150 Résistance Élémentaire.",
    "Critique Berserk": "Lorsque les PV sont inférieurs à 50 % :\n5 % Coup Critique.",
    "Visibilité": "1 Portée.\n-300 Tacle.\n-300 Esquive.",
    "Tacle Berserk": "Lorsque les PV sont inférieurs à 50 % :\n10 % Tacle.",
    "Embuscade écartée": "4 % Dommages Infligés aux cibles à 2 cases (1 case entre le porteur de l'état et sa cible).",
    "Epines": "Effectue une Parade donne Préparation +1 Niv. (max 60) (+1 % Dommages Infligés au prochain sort/niveau).",
    "Esquive Berserk": "Lorsque les PV sont inférieurs à 50% :\n10 % Esquive.",
    "Barrière Distance": "Réduit les Dommages Distance subis de 50% du niveau, 2 fois par tour.",
    "Barrière Mêlée": "Réduit les Dommages Mêlée subis de 50% du niveau, 2 fois par tour.",
    "Opiniâtreté": "Après avoir subi une perte de 2 PA :\n5 Volonté (3 tours).",
    "Aisance": "Après avoir subi une perte de 2 PM :\n5 Volonté (3 tours).",
    "Parade Berserk": "Lorsque les PV sont inférieurs à 50 % :\n5% Parade.",
    "Puits de Vitalité": "Augmente de 5 % les Vols de vie réalisés.",
    "Influence": "3 % Coup Critique.",
    "Muraille": "En début de combat, 150 % du niveau en Armure.",
    "Cyclothymie": "Tour pair : 10 Volonté.\nTour impair : -10 Volonté.",
    "Prospérité": "3 % aux bonus de caractéristiques reçus.\nConcerne tous les bonus de caractéristiques (Maîtrises, Résistances, Armure) reçus en combat, lancés par une entité autre que le porteur de l'état.\nLa valeur est toujours arrondie à l'inférieur.",
    "Longueur": "2 % Dommages Infligés aux cibles alignées et à 2 cases et plus du porteur de l'état.",
    "Enveloppe rocheuse": "3 % Armure donnée.",
    "Influence lente": "1 % Coup Critique par tour (max 30).",
    "Expert des Coups Critiques": "En fin de tour, si un coup critique a été effectué :\nSoin : 2 % des PV manquants du lanceur.",
    "Stupéfaction": "En début de combat :\n5% Coup Critique (1 tour).\n5 % du niveau en Maîtrise Critique (1 tour).",
    "Intégrité": "En soignant un allié, si cet allié a moins de 15% PV :\nSoin : 7 % des PV max de la cible.",
    "Loup solitaire": "Si aucun allié n'est entre 1 et 4 cases du porteur :\n2 % Dommages Infligés.",
    "Tolérance": "En fin de tour :\n50 % des PM non utilisés sont transmis au tour suivant (max 1 PM).",
    "Arme solide": "En infligeant des dommages à un ennemi avec une arme :\nCet ennemi réduit ses dommages sur le porteur de l'état de -5 % (1 tour, non-cumulable).\nLe porteur de l'état doit posséder un bouclier équipé.",
    "Puissance brute": "En début de combat :\n-1 PW max.\nPour chaque PW dépensé au cours du tour :\n2 % Dommages infligés (1 tour) (max 16).",
    "Retour enflammé": "Gagne 100 % du niveau en Enflammé en tuant un ennemi (1 activation par tour).",
    "Influence du Wakfu": "Lorsque le porteur de l'état commence son tour avec tous ses PW (ou toute sa BQ) :\n10 % Coup Critique (1 tour).",
    "Wakfu Berserk": "Lorsque le porteur de l'état commence son tour avec 50 % ou moins de ses PW (ou de sa BQ) :\n3 % Dommages critiques infligés (1 tour).\n100 % du niveau en Armure.",
    "Arme empoisonnée": "-20 % Dommages Infligés (+5 % par niveau supplémentaire) avec une Arme.\nEn infligeant des dommages à un ennemi avec une arme à deux mains :\nIncurable (niveau : coût en PA de l'arme) sur l'ennemi et le porteur de l'état.",
    "Vol de Tacle": "-10 % Dommages Infligés avec une arme\nEn infligeant des dommages à un ennemi avec une arme à deux mains :\nVole 15 % du niveau en Tacle (1 tour, non-cumulable).",
    "Vol d'Esquive": "-10 % Dommages Infligés avec une arme\nEn infligeant des dommages à un ennemi avec une arme à deux mains :\nVole 15 % du niveau en Esquive (1 tour, non-cumulable).",
    "Contre-attaque": "Lorsque le porteur de l'état subit des dommages directs au contact, une fois par tour de l'attaquant :\nLe porteur de l'état lui inflige des dommages lumière (10 % du niveau).",
    "Expert des armes légères": "Si aucun bouclier, ni dague, ni arme à deux mains n'est équipé, en début de combat :\n25 % du niveau en Maîtrise Élémentaire.\n2 % Dommages Infligés sur une cible avec de l'Armure.",
    "Arcanes": "Si le porteur de l'état ne possède pas d'armure en fin de tour :\n50 % du niveau en Armure.",
    "Relations sociales": "2 % Dommages dos en tour pair.\n2 % Dommages de face en tour impair.",
    "Retour vital": "Soin : 10 % des PV manquants du lanceur en tuant un ennemi (2 activations par tour).",
    "Destruction": "3 % Dommages de dos.\n-2 % Dommages de face et de côté.",
    "Être sensible": "Si deux alliés ou plus sont entre 1 et 4 cases du porteur :\n2 % Dommages Infligés.",
    "Longueur d'armure": "4 % Armure donnée sur un allié en ligne et à distance.",
    "Altruisme": "2 % Soins réalisés sur un allié en ligne et à distance.",
    "Manie": "Les dommages en mêlée retirent 50 % du niveau en Armure sur la cible.\n-3 % Armure reçue.",
    "Nature": "2 % Soins réalisés sur un allié au contact d'un autre allié.",
    "Dernier souffle": "Lorsque le porteur commence son tour en dessous de 20 % PV :\n3% Dommages Infligés (1 tour).\n50 % du niveau en armure.",
    "Main forte": "Finir son tour au contact d'un ennemi lui applique -5 % Armure reçue (1 tour).",
    "Pied ferme": "Finir son tour au contact d'un ennemi lui applique -5 % Soins réalisés (1 tour).",
    "Volte-face": "Lorsque le porteur de l'état subit des dommages directs au contact, une fois par tour de l'attaquant :\nLe porteur de l'état se tourne vers lui.",
    "Courage": "2 % dommages et soins non-critiques infligés.\n-2 % dommages et soins critiques infligés.",
    "Revigoration": "-10 % Soins réalisés.\nLe porteur de l'état est soigné de 4 % des soins réalisés sur ses alliés.",
    "Précaution": "En terminant son tour avec moins de 50 % de PV :\nSoin : 5 % des PV manquants.",
    "Critique technique": "Le premier coup critique du tour inflige 12 % Dommages supplémentaires.\nLes suivants infligent 6 % Dommages de moins.",
    "Parade offensive": "En faisant une parade sur une attaque directe ennemie :\n4 % Dommages infligés (1 tour).\n-10% Parade (1 tour).",
    "Critique tactique": "3 % Dommages critiques infligés si la cible a > 50 % PV.\n-3 % Dommages critiques infligés si la cible a <= 50 % PV.",
    "Neutralité": "Au début du premier tour, si les maîtrises secondaires sont <= 0 :\n8 % Dommages infligés.",
    "Abandon": "Au début du premier tour, si les maîtrises secondaires sont <= 0 :\n1 PW max et 1 Portée.\n-10 % Armure donnée et reçue.",
    "Prétention": "Au début du premier tour, si les maîtrises secondaires sont <= 0 :\n5 % Parade.",
    "Armure lourde": "-1 PM.\n5 % Dommages infligés.",
    "Carapace": "-2 PA.\n75 Résistance élémentaire.",
    "Combat rapproché": "-1 Portée.\n50% du niveau en Tacle et Esquive.",
    "Préparation critique": "À chaque coup critique effectué :\n+2 Préparation pour le tour suivant (5 activations par tour).",
    "Temporisation": "En début de tour, si le joueur n'a pas utilisé de PW le tour précédent :\n4 % Dommages infligés.\n4 % Soins réalisés.",
    "Verrouillage": "4 % Dommages infligés aux cibles sans ligne de vue et à 3 cases ou plus.",
    "Poids plume": "Au lancement du combat, par PM au-dessus de 4 :\n2 % Dommages infligés (24 maximum).",
    "Ambition": "Au début du premier tour, si les maîtrises secondaires sont <= 0 :\n5 % Coup critique.",
    "Art du cachement": "-6% Dommages reçus si le porteur est hors ligne de vue.\n3% Dommages reçus sinon.",
    "Folie": "6% Dommages infligés en diagonale.",
    "Tabass'Carapace": "6% Dommages infligés sur une cible qui possède de l'Armure.",
    "Témérité": "Lorsque le porteur retire toute son Armure à une cible :\n3% Dommages infligés pour le reste du tour (max 30%).",
    "Folie vampirique": "-20% Soins reçus.\nLorsque le porteur inflige des dommages en diagonale :\nVole 4% des dommages infligés.",
    "Accumulation": "-20% Soins réalisés.\nChaque tour passé sans soigner :\n5% Soins réalisés (max 40%).",
    "Conservation": "Lorsque les PV sont supérieurs à 90% :\n10% Parade.",
    "Carapace sanguine": "En début de tour :\nConvertit 10% des PV courants en Armure.",
    "Profit": "Regagne 1 PA en retirant 1 PA ou 1 PM à un ennemi (1 max par tour).",
    "Retour d'Armure": "Regagne 5% des PV max en Armure en tuant un ennemi (2 activations par tour).",
    "Force légère": "Tant que le porteur ne possède pas d'Armure :\n3% Dommages infligés.",
    "Agilité vitale": "En début de tour, si les PV sont supérieurs à 90% :\n1 PM.",
    "Influence vitale": "Lorsque les PV sont supérieurs à 90% :\n4% Coup critique.",
    "Force vitale": "En début de tour, si les PV sont supérieurs à 90% :\n1 PA.",
    "Évasion": "En début de combat :\n50% du niveau en Esquive.",
    "Fuite": "Après avoir esquivé (avec pertes) :\n1 PM (1 max par tour)",
    "Interception": "En début de combat :\n50% du niveau en Tacle.",
    "Interposition": "Après avoir taclé un ennemi :\n50% du niveau en Armure.",
    "Influence paradoxale": "Si un coup non critique est effectué avec un sort élémentaire :\n5% Coup critique au tour suivant.",
    "Acribie": "2 % Dommages infligés aux cibles à 5 cases ou plus.",
    "Allocentrisme": "Si le porteur ne possède pas d'Armure :\n5 % Armure Donnée.",
    "Apprêt": "En fin de tour, par ennemi au corps-à-corps :\n1 % Dommages infligés pour le tour suivant.",
    "Balance critique": "À chaque sort non-critique effectué :\n2 % Coup critique (cumulable). Le bonus est perdu au prochain Coup critique.",
    "Bouclier critique": "5 Résistance critique.",
    "Bouclier dorsal": "5 Résistance dos.",
    "Brûlure": "4 % Dommages infligés dans l'élément Feu.",
    "Brûlure secondaire": "En lançant un sort élémentaire Eau, Terre ou Air :\n2 % Dommages infligés dans l'élément Feu (cumulable, max 30 %). L'effet est consommé aux prochains dommages directs Feu.",
    "Consolation critique": "À chaque sort non-critique effectué :\n2 % Dommages infligés en Coup critique (cumulable, max 40 %). Le bonus est perdu au prochain Coup critique.",
    "Dernier soin": "En tombant sous 20 % PV max (1 fois par combat) :\n5 % des PV max en Soin.",
    "Dernière Armure": "En tombant sous 20 % PV max (1 fois par combat) :\n5 % des PV max en Armure.",
    "Dernières résistances": "En tombant sous 20 % PV max (1 fois par combat) :\n20 Résistance élémentaire (1 tour).",
    "Dérobade continue": "3 % Parade.",
    "Gel": "4 % Dommages infligés dans l'élément Eau.",
    "Gel secondaire": "En lançant un sort élémentaire Feu, Terre ou Air :\n2 % Dommages infligés dans l'élément Eau (cumulable, max 30 %). L'effet est consommé aux prochains dommages directs Eau.",
    "Propagation": "Lorsque le porteur inflige des dommages, une fois par tour :\nInflige 10 % du niveau en dommages lumière aux cibles alignées avec la cible.",
    "Représaille": "Lorsque le porteur de l'état subit des dommages directs à distance :\nInflige 6 % Dommages supplémentaires à l'attaquant (1 tour, non cumulable).",
    "Rupture PA": "Pendant son tour, lorsque le porteur de l'état fait perdre son Armure à un ennemi :\nRegagne 1 PA (max 2 fois/tour).",
    "Rupture violente": "Pendant son tour, lorsque le porteur de l'état fait perdre son Armure à un ennemi :\nInflige 10 % du niveau en dommages lumières (max 2 fois/tour).",
    "Sanguinolence": "À chaque malus ou perte appliqués sur une cible :\nLui applique Vulnérabilité (2 niveaux) (1 tour).\n1 % dommages reçus par le porteur par niveau. Max 40 %.",
    "Sauvegarde du Wakfu": "-1 PW max.\nEn fin de tour, si le porteur n'a pas dépensé de PW :\n+1 PW.",
    "Tellurisme": "4 % Dommages infligés dans l'élément Terre.",
    "Tellurisme secondaire": "En lançant un sort élémentaire Feu, Eau ou Air :\n2 % Dommages infligés dans l'élément Terre (cumulable, max 30 %). L'effet est consommé aux prochains dommages directs Terre.",
    "Valeur ajoutée": "À chaque dommage indirect effectué :\n-2 % Dommages directs (1 tour)\n+4 % Dommages indirects (1 tour)\nMax 40 %.",
    "Ventilation": "4 % Dommages infligés dans l'élément Air.",
    "Ventilation secondaire": "En lançant un sort élémentaire Feu, Eau ou Terre :\n2 % Dommages infligés dans l'élément Air (cumulable, max 30 %). L'effet est consommé aux prochains dommages directs Air.",
    "Vision intermédiaire": "3 % Dommages infligés aux cibles à 3 cases.",
    "Volonté directe": "En dehors du tour du porteur : -4 Volonté.\nPendant le tour du porteur : 3 Volonté.",
    "Volonté indirecte": "En dehors du tour du porteur : 3 Volonté.\nPendant le tour du porteur : -4 Volonté.",
    "Sauvegarde critique": "En fin de tour : Les PA non utilisés sont transmis en Coup critique au tour suivant.\n10 % Coup Critique par PA.\nMax : 1 PA.",
    "Diagnostic": "En soignant un allié en monocible :\n2 % Soins réalisés supplémentaires sur cette cible au prochain tour.",
    "Jugement": "En infligeant des dommages en monocible à un ennemi :\n3 % Dommages infligés supplémentaires sur cette cible au prochain tour.",
    "Élan": "Si le porteur se déplace avec un sort :\nPréparation (+5 niveau).",
    "Apprêt secondaire": "En fin de tour, si un ennemi est au contact :\n2 % Dommages infligés pour le tour suivant."
}

# Charger le fichier JSON
with open('c:\\Users\\maxer\\IdeaProjects\\Wakfu Builder\\public\\sublimations.json', 'r', encoding='utf-8') as f:
    sublimations = json.load(f)

# Mettre à jour les descriptions
updated_count = 0
for subli in sublimations:
    title_fr = subli['title']['fr']
    if title_fr in descriptions_fr and subli['description']['fr'] == "":
        subli['description']['fr'] = descriptions_fr[title_fr]
        updated_count += 1
        print(f"✓ Mis à jour: {title_fr}")

# Sauvegarder le fichier
with open('c:\\Users\\maxer\\IdeaProjects\\Wakfu Builder\\public\\sublimations.json', 'w', encoding='utf-8') as f:
    json.dump(sublimations, f, ensure_ascii=False, indent=2)

print(f"\n{updated_count} descriptions mises à jour avec succès!")
